# Generated by Django 5.0.1 on 2024-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='contact',
            name='s_no',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
